cy_email= '//div[@id="usernameForm"]//input[1][@type="email"][1]'
cy_button= '//div[@id="usernameForm"]//button[text()="Next"]'
cy_pass= '//input[@type="password"]'
cy_butpas= '//input[@id="idSIButton9"]'
cy_yes= '//input[@id="idSIButton9"]'
cy_signinbut= '//button[text()="Sign In"]'
cy_search = '//input[@id="jsutil-text-1110-inputEl"]'
cy_cmpltmeri= '//a[text()="Meridian Complete_bgajjar@empclaims.com"]'
logo='//img[@src="/static/provider/img/logos/78-provider.png"]'
email_field='//div//input[@id="identifierInput"]'
login_field='//div//a[@class="ping-button normal allow"]'
pass_field='//input[@id="password"]'
tin_field='//select[@id="providerProfileId"]'
tin_option1_medicaid='//option[@value="201644291"]'
tin_option2_medicaid='//option[@value="273698244"]'
tin_option3_medicaid='//option[@value="382896881"]'
tin_option4_medicaid='//option[@value="383544427"]'
tin_option5_medicaid='//option[@value="412153406"]'
tin_option6_medicaid='//option[@value="813174547"]'
plan_type='//select[@id="providerProfileName"]'
go_button='//button[@id="medicalDropdownSubmitID"]'
plan_type_medicaid='//option[@value="7700545"]'
plan_type_mmp_medicare='//option[contains(text(),"MI MMP Medicare")]'
plan_type_mmp_medicaid='//select[@id="providerProfileName"]//option[4]'
claims= '//div//li//a[@href="/careconnect/claims/viewClaimsHome"]'
change_date= '//a[text()="Change dates"]'
from_date= '//input[@id="dosFrom"]'
to_date= '//input[@id="dosTo"]'
search= '//button[text()="Search"]'
claim_NO= '//tbody//a'
claim_enter= '//div[contains(text(),"Claim")]'
back_claim= '//a[contains(text(),"Back")]'
error= '//header[contains(text(),"Oops")]'
reload='//img[@src="/static/provider/img/logos/78-provider.png"]'
